---
title: "References For Lab Website - Academic theme in Hugo"
author: "Anthony J. Richardson"
date: "06/05/2020"
output: html_document
---

# Instructions
These instructions are for creating an automatic reference list for the lab website. The labsite uses Hugo and the Academic theme.

See https://sourcethemes.com/academic/docs/managing-content/#create-a-publication for general help on how to do this.

The aim is to create a folder for each publication in the (default) `/Website_SourceCode/content/publication` folder for your website. Each folder will contain a `cite.bib` file and an `index.md` markdown file. The `index.md` is the one used in the website and is created from the `cite.bib` file (which is created from the BibTeX file for all your publications).

You can export a list of your publications in BibTeX format from Web Of Science, but it is probably easiest from reference manager software. I use `Zotero` to manage my references and so will describe that process. 

1. In Zotero, create a library with all your  publications in it. Any you want to export highlight them (or `ctrl-A` to highlight all) and right-click to `Export Items`, choose the `BibTeX` format, and uncheck all the options because you don't need them. This will export your highlighted references in one `BibTeX` file named `Exported Items.bib`. Put it in your `Website_SourceCode` folder (the home folder for your website source code). 

2. To convert the references into the right format for the website, you need to run a line of code at the Terminal. This code requires `Python` version 3. If you haven't got it, then see See https://sourcethemes.com/academic/docs/managing-content/#create-a-publication to install it. On my Mac, I had to install `Homebrew` first, then Install `Python.` It worked.

3. In the Terminal, change the directory (using `cd ..` to go up etc.) so you are in  your `Website_SourceCode` folder. Then run the line:

`academic import --bibtex Exported\ Items.bib`

The `Exported\ Items.bib` is the file export from Zotero, with the `\ ` for a space in the filename. I simply pasted the `Exported Items.bib` filename into the Terminal.

4. When this command is run, it will create a folder for each of your publications in `/Website_SourceCode/content/publication`. It will give `WARNING`s when the folder is already present and `ERROR`s if it doesn't have a critical piece of information (most commonly it needs a Date) to build the reference. The easiest way to fix these is to sort it out in `Zotero` and re-export.

5. The easiest way to update your publications is to update them in Zotero and then re-export as above. Note that it is often useful to delete all the folders produced in `/Website_SourceCode/content/publication` before re-running the `academic import` command because if you change say a title or date of the publication in `Zotero`, then it could change the folder for your website and leave the old one, producing multiple versions of the same reference. (NOTE: DON'T DELETE THE `_index.md` `MARKDOWN` FILE THAT CONTROLS THE OVERALL REFERENCE OUTPUT FORMAT FOR THE WEBSITE).
